<?php
declare(strict_types=1);

$configPath = __DIR__ . '/../config.php';
$alreadyInstalled = file_exists($configPath);
$error = null;
$success = false;

if (!$alreadyInstalled && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = trim($_POST['db_host'] ?? '');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';
    $adminUser = trim($_POST['admin_user'] ?? '');
    $adminPass = $_POST['admin_pass'] ?? '';
    $adminPassConfirm = $_POST['admin_pass_confirm'] ?? '';

    if ($dbHost === '' || $dbName === '' || $dbUser === '' || $adminUser === '' || $adminPass === '') {
        $error = 'الرجاء تعبئة جميع الحقول';
    } elseif ($adminPass !== $adminPassConfirm) {
        $error = 'كلمتا المرور غير متطابقتين';
    } elseif (strlen($adminPass) < 8) {
        $error = 'كلمة المرور يجب أن تكون 8 أحرف على الأقل';
    } else {
        try {
            $pdo = new PDO(
                "mysql:host={$dbHost};dbname={$dbName};charset=utf8mb4",
                $dbUser,
                $dbPass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );

            $pdo->exec("CREATE TABLE IF NOT EXISTS packs (
                id VARCHAR(64) PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                version INT NOT NULL DEFAULT 1,
                updated_at BIGINT NOT NULL,
                created_at BIGINT NOT NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            $pdo->exec("CREATE TABLE IF NOT EXISTS puzzles (
                id VARCHAR(64) PRIMARY KEY,
                pack_id VARCHAR(64) NOT NULL,
                title VARCHAR(255) NOT NULL,
                rows INT NOT NULL,
                cols INT NOT NULL,
                words_json JSON NOT NULL,
                CONSTRAINT fk_puzzles_pack FOREIGN KEY (pack_id) REFERENCES packs(id) ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            $pdo->exec("CREATE INDEX idx_puzzles_pack ON puzzles(pack_id)");

            $pdo->exec("CREATE TABLE IF NOT EXISTS admin_users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                username VARCHAR(64) UNIQUE NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                created_at BIGINT NOT NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            $existing = $pdo->prepare('SELECT COUNT(*) FROM admin_users WHERE username = :u');
            $existing->execute([':u' => $adminUser]);
            if ((int)$existing->fetchColumn() > 0) {
                throw new RuntimeException("يوجد مستخدم بهذا الاسم بالفعل. اختر اسماً آخر أو احذف جدول admin_users وأعد المحاولة.");
            }

            $stmt = $pdo->prepare('INSERT INTO admin_users (username, password_hash, created_at) VALUES (:u, :p, :c)');
            $stmt->execute([
                ':u' => $adminUser,
                ':p' => password_hash($adminPass, PASSWORD_DEFAULT),
                ':c' => (int)round(microtime(true) * 1000),
            ]);

            $configContent = "<?php\n"
                . "// Generated by the installer on " . date('Y-m-d H:i:s') . ".\n"
                . "// Do not commit this file to version control.\n"
                . "return [\n"
                . "    'db' => [\n"
                . "        'host'    => " . var_export($dbHost, true) . ",\n"
                . "        'name'    => " . var_export($dbName, true) . ",\n"
                . "        'user'    => " . var_export($dbUser, true) . ",\n"
                . "        'pass'    => " . var_export($dbPass, true) . ",\n"
                . "        'charset' => 'utf8mb4',\n"
                . "    ],\n"
                . "];\n";

            if (file_put_contents($configPath, $configContent) === false) {
                throw new RuntimeException('تعذّرت الكتابة إلى config.php — تحقق من صلاحيات المجلد (يجب أن يكون قابلاً للكتابة).');
            }

            $success = true;
        } catch (PDOException $e) {
            $error = 'فشل الاتصال بقاعدة البيانات: ' . $e->getMessage();
        } catch (Throwable $e) {
            $error = $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>تثبيت كلمات مسهمة</title>
<style>
  :root{ --ink:#111; --paper:#fdfcf8; --page:#e7e4da; --accent:#b8862f; }
  *{box-sizing:border-box}
  body{ font-family:-apple-system,Tahoma,Arial,sans-serif; background:var(--page); color:var(--ink); margin:0; padding:24px 14px; }
  .card{ max-width:480px; margin:0 auto; background:var(--paper); border:2px solid var(--ink); padding:26px 22px; }
  h1{ font-size:1.3rem; margin:0 0 4px; }
  p.sub{ color:#555; font-size:0.85rem; margin:0 0 20px; }
  fieldset{ border:1px solid #ccc; margin-bottom:16px; padding:12px 14px; }
  legend{ font-size:0.8rem; font-weight:700; padding:0 6px; }
  label{ display:block; font-size:0.82rem; font-weight:600; margin:10px 0 4px; }
  input{ width:100%; padding:9px 10px; border:1.5px solid var(--ink); font-size:0.9rem; background:#fff; }
  button{ width:100%; margin-top:18px; padding:12px; background:var(--ink); color:var(--paper); border:none; font-weight:700; font-size:0.95rem; cursor:pointer; }
  .error{ background:#eec3bd; border:1.5px solid #a5453a; padding:10px 12px; font-size:0.85rem; margin-bottom:16px; }
  .success{ background:#c9e0c4; border:1.5px solid #4c7a5d; padding:16px; font-size:0.9rem; }
  .success a{ display:inline-block; margin-top:10px; background:var(--ink); color:var(--paper); padding:9px 18px; text-decoration:none; font-weight:700; }
  .note{ background:#f1efe6; border:1px solid #ccc; padding:10px 12px; font-size:0.78rem; color:#444; margin-top:16px; }
</style>
</head>
<body>
<div class="card">
  <h1>تثبيت كلمات مسهمة</h1>
  <p class="sub">إعداد قاعدة البيانات وحساب المسؤول — خطوة واحدة فقط.</p>

  <?php if ($alreadyInstalled && !$success): ?>
    <div class="error">
      التطبيق مثبّت بالفعل (يوجد ملف config.php). لإعادة التثبيت، احذف config.php من المجلد الرئيسي أولاً.
    </div>
    <a href="../admin/login.php">الذهاب إلى لوحة التحكم</a>

  <?php elseif ($success): ?>
    <div class="success">
      تم التثبيت بنجاح ✅
      <br>يمكنك الآن تسجيل الدخول إلى لوحة التحكم.
      <br><a href="../admin/login.php">تسجيل الدخول</a>
    </div>
    <div class="note">
      لأسباب أمنية، يُفضّل حذف مجلد <code>install/</code> بالكامل الآن (أو إعادة تسميته) — لن تحتاجه مرة أخرى.
    </div>

  <?php else: ?>
    <?php if ($error): ?><div class="error"><?= htmlspecialchars($error) ?></div><?php endif; ?>
    <form method="post">
      <fieldset>
        <legend>بيانات قاعدة البيانات (من cPanel)</legend>
        <label>المضيف Host</label>
        <input name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" required>
        <label>اسم القاعدة (عادة يبدأ باسم حسابك، مثل cpaneluser_arrowwords)</label>
        <input name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? '') ?>" required>
        <label>اسم المستخدم</label>
        <input name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" required>
        <label>كلمة المرور</label>
        <input type="password" name="db_pass" required>
      </fieldset>

      <fieldset>
        <legend>حساب المسؤول (لوحة التحكم)</legend>
        <label>اسم المستخدم</label>
        <input name="admin_user" value="<?= htmlspecialchars($_POST['admin_user'] ?? '') ?>" required>
        <label>كلمة المرور (8 أحرف على الأقل)</label>
        <input type="password" name="admin_pass" required minlength="8">
        <label>تأكيد كلمة المرور</label>
        <input type="password" name="admin_pass_confirm" required minlength="8">
      </fieldset>

      <button type="submit">تثبيت</button>
    </form>
    <div class="note">
      تأكد أنك أنشأت قاعدة البيانات والمستخدم من cPanel → MySQL® Databases أولاً، وأضفت المستخدم إلى القاعدة بكل الصلاحيات. هذا المثبّت لا يُنشئ قاعدة بيانات جديدة، فقط الجداول داخلها.
    </div>
  <?php endif; ?>
</div>
</body>
</html>
